var DotMatrixLoader=(()=>{var h=Object.defineProperty;var q=Object.getOwnPropertyDescriptor;var N=Object.getOwnPropertyNames;var O=Object.prototype.hasOwnProperty;var D=(t,e)=>{for(var n in e)h(t,n,{get:e[n],enumerable:!0})},j=(t,e,n,r)=>{if(e&&typeof e=="object"||typeof e=="function")for(let o of N(e))!O.call(t,o)&&o!==n&&h(t,o,{get:()=>e[o],enumerable:!(r=q(e,o))||r.enumerable});return t};var B=t=>j(h({},"__esModule",{value:!0}),t);var F={};D(F,{createLoader:()=>C,patterns:()=>f});var M=!1;function k(){if(M||typeof document>"u")return;M=!0;let t=document.createElement("style");t.setAttribute("data-dotmatrix-loader",""),t.textContent=`
.dl-loader { display: inline-block; }
.dl-dot {
  animation: dl-blink var(--dl-duration, 1.2s) linear infinite;
}
.dl-loader.dl-paused .dl-dot {
  animation-play-state: paused;
}
@keyframes dl-blink {
  0%, 49% { fill: var(--dl-off); opacity: var(--dl-min-opacity, 1); }
  50%, 99% { fill: var(--dl-on); opacity: 1; }
  100% { fill: var(--dl-off); opacity: var(--dl-min-opacity, 1); }
}
`,document.head.appendChild(t)}var P=(t,e,n)=>{let r=(n-1)/2;return Math.hypot(t-r,e-r)},G=(t,e,n)=>{let r=(n-1)/2;return(Math.atan2(t-r,e-r)+Math.PI)/(2*Math.PI)},V=(t,e,n)=>{let r=Math.sin((t*n+e+1)*12.9898)*43758.5453;return r-Math.floor(r)},f={pulse:(t,e,n)=>P(t,e,n),wave:(t,e)=>t+e,rowSweep:t=>t,columnSweep:(t,e)=>e,orbit:(t,e,n)=>G(t,e,n),checker:(t,e)=>(t+e)%2,heartbeat:(t,e,n)=>P(t,e,n)<.8?0:null,sparkle:(t,e,n)=>V(t,e,n)};var $="http://www.w3.org/2000/svg",_=0;function z(t,e){let n=[];for(let a=0;a<t;a++)for(let d=0;d<t;d++)n.push(e(a,d,t));let r=n.filter(a=>a!=null),o=Math.min(...r),u=Math.max(...r)-o||1;return n.map(a=>a==null?null:(a-o)/u)}function C(t,e={}){k();let{pattern:n="pulse",size:r=5,dotSize:o=6,gap:c=4,duration:u=1.2,colorOn:a="#111111",colorOff:d="#e2e2e2",minOpacity:E=.2,shape:S="circle"}=e,I=`dl-${++_}`,i=document.createElementNS($,"svg");i.setAttribute("class","dl-loader"),i.dataset.dlId=I;let p=r*o+(r-1)*c;i.setAttribute("viewBox",`0 0 ${p} ${p}`),i.setAttribute("width",String(p)),i.setAttribute("height",String(p)),i.style.setProperty("--dl-on",a),i.style.setProperty("--dl-off",d),i.style.setProperty("--dl-duration",`${u}s`),i.style.setProperty("--dl-min-opacity",String(E));function b(s){i.replaceChildren();let g=typeof s=="function"?s:f[s];if(!g)throw new Error(`dotmatrix-loader: unknown pattern "${s}"`);let L=z(r,g),w=0;for(let y=0;y<r;y++)for(let m=0;m<r;m++,w++){let x=m*(o+c)+o/2,A=y*(o+c)+o/2,l=document.createElementNS($,S==="square"?"rect":"circle");l.setAttribute("class","dl-dot"),S==="square"?(l.setAttribute("x",String(x-o/2)),l.setAttribute("y",String(A-o/2)),l.setAttribute("width",String(o)),l.setAttribute("height",String(o))):(l.setAttribute("cx",String(x)),l.setAttribute("cy",String(A)),l.setAttribute("r",String(o/2)));let v=L[w];v===null?(l.dataset.static="",l.style.animation="none",l.style.fill="var(--dl-off)",l.style.opacity="var(--dl-min-opacity)"):l.style.animationDelay=`${v*u}s`,i.appendChild(l)}}if(b(n),t){let s=typeof t=="string"?document.querySelector(t):t;s&&s.appendChild(i)}return{el:i,start(){i.classList.remove("dl-paused")},stop(){i.classList.add("dl-paused")},setPattern(s){b(s)},destroy(){i.remove()}}}return B(F);})();
//# sourceMappingURL=dotmatrix-loader.js.map
